function get_set(set){
    if(set==1){
        var raw=[['q1','a1'],['q2','a2']];//[["el campeonato","championship"],["el ciclismo","bicycle racing"],["la competencia","competition"],["competir","to compete"],["estar empatado","to be tied"],["jugar en equipo","to play on a team"],["meter un gol","to score a goal"],["el premio","prize; award"],["la Copa Mundial","The World Cup"],["los Juegos Olímpicos","The Olympic Games"],["los Juegos Panamericanos","The Panamerican Games"],["la Vuelta a Francia","the Tour de France"],["la pista","track"],["la red","net"],["el uniforme","uniform"],["¡Ay, por favor!","Oh, please!"],["¡Bravo!","Bravo!"],["¡Dale!","Come on!"],["¡Uy!","Ugh!"],["activo","active"],["el deportista","sportsman"],["lento","slow"],["musculoso","muscular"],["rápido","fast"],["Es bueno","It's good"],["Es importante","It's important"],["Es necesario","it's necessary"],["hacer ejercicio","to exercise"],["mantenerse en forma","to stay in shape"],["saludable","healthy"],["seguir una dieta balanceada","to follow a balanced diet"],["el arco","goal"],["el cesto; la canasta; el aro","hoop; basket"],["los esquís","skis"],["los guantes de boxeo","boxing gloves"],["el arquero","goalkeeper"],["el bateador","batter"],["el lanzador","pitcher"],["el porrista","cheerleader"],["el árbitro","umpire"],["batear","to bat"],["el boxeo","boxing"],["caerse","to fall"],["la carrera","race"],["la ginmasia","gymnastics"],["hacer un aro","to make a basket"],["la lucha","wrestling"],["saltar","to jump"],["practicar yoga","to do yoga"],["perder peso","to lose weight"],["subir de peso","to gain weight"],["usar las máquinas para hacer ejercicio","to use exercise machines"],["el básquetbol","basketball"],["el béisbol","baseball"],["el fútbol americano","football"],["ganar","to win"],["la natación","swimming"],["perder","to lose"],["el tenis","tennis"],["el voleibol","volleyball"],["el bate","bat"],["el casco","helmet"],["el guante","glove"],["los patines en línea","rollerblades"],["la pelota","ball"],["la raqueta","racket"],["los aficionados","fans"],["el campeón","champion (masculine)"],["la campeona","champion (feminine)"],["el campo","field"],["la cancha","court"],["el equipo","team"],["el ganador","winner"],["el jugador","player"],["doler","to hurt; to ache"],["fuerte","strong"],["heriod","hurt"],["la saldud","health"],["sano","healthy"]];
    }
    if(set==2){
        var raw=[["acostarse ","to go to bed"],["afeitarse ","to shave oneself"],["apagar la luz ","to turn off the light"],["arreglarse ","to get ready"],["bañarse ","to take a bath"],["cepillarse los dientes ","to brush one's teeth"],["despertarse ","to wake up"],["dormirse ","to fall asleep"],["ducharse ","to take a shower"],["encender la luz ","to turn on the light"],["entrenarse ","to train"],["lavarse ","to wash oneself"],["levantarse ","to get up"],["maquillarse ","to put on makeup"],["peinarse ","to comb one's hair"],["la rutina ","routine"],["secarse ","to dry oneself"],["tener prisa ","to be in a hurry"],["tener sueño ","to be sleepy"],["la cara ","face"],["el codo ","elbow"],["el cuello ","neck"],["el dedo ","finger"],["el dedo de pie ","toe"],["el diente ","tooth"],["la garaganta ","throat"],["el hombro ","schoulder"],["la muñeca ","wrist"],["el oído ","inner ear"],["la uña ","nail"],["el cepillo ","brush"],["el cepillo de dientes ","toothbrush"],["el champú ","shampoo"],["la crema de afeitar ","shaving cream"],["el desodorante ","deodorant"],["el jabón ","soap"],["la pasta de dientes ","toothpaste"],["el peine ","comb"],["el secador de pelo ","hair dryer"],["la toalla ","towel"],["primero ","first"],["entonces ","then; so"],["luego ","later; then"],["más tarde ","later on"],["por fin ","finally"],["a veces ","sometimes"],["frecuentemente ","frequently"],["generalmente ","in general; generally"],["normalmente ","usually; normally"],["la boca ","mouth"],["el brazo ","arm"],["la cabeza ","head"],["el corazón ","heart"],["el cuerpo ","body"],["el estómago ","stomach"],["la mano ","hand"],["la nariz ","nose"],["el ojo ","eye"],["lo oreja ","ear"],["el pelo ","hair"],["el pie ","foot"],["la piel ","skin"],["la pierna ","leg"],["la rodilla ","knee"],["el tobillo ","ankle"],["tener ","to have"],["tener ganas de ","to feel like"],["tener que ","to have to"],["alisarse el pelo ","to straighten one's hair"],["la base ","foundation"],["la colonia ","cologne"],["cortarse el pelo ","to cut one's hair"],["los cortaúñas ","nail clippers"],["el esmalte ","nailpolish"],["la loción para después de afeitarse ","aftershave"],["el perfume ","perfume"],["el pintalabios ","lipstick"],["el lápiz ","lipstick"],["pintarse el pelo ","to color one's hair"],["pintarse las uñas ","to color one's nails"],["el rímel ","mascara"],["rizarse el pelo ","to curl one's hair"],["la seda dental ","dental floss"],["la sombra de ojos ","eye shadow"],["los pulmones ","lungs"]];
    }
    if(set==3){
        var rw1=[["el campeonato","championship"],["el ciclismo","bicycle racing"],["la competencia","competition"],["competir","to compete"],["estar empatado","to be tied"],["jugar en equipo","to play on a team"],["meter un gol","to score a goal"],["el premio","prize; award"],["la Copa Mundial","The World Cup"],["los Juegos Olímpicos","The Olympic Games"],["los Juegos Panamericanos","The Panamerican Games"],["la Vuelta a Francia","the Tour de France"],["la pista","track"],["la red","net"],["el uniforme","uniform"],["¡Ay, por favor!","Oh, please!"],["¡Bravo!","Bravo!"],["¡Dale!","Come on!"],["¡Uy!","Ugh!"],["activo","active"],["el deportista","sportsman"],["lento","slow"],["musculoso","muscular"],["rápido","fast"],["Es bueno","It's good"],["Es importante","It's important"],["Es necesario","it's necessary"],["hacer ejercicio","to exercise"],["mantenerse en forma","to stay in shape"],["saludable","healthy"],["seguir una dieta balanceada","to follow a balanced diet"],["el arco","goal"],["el cesto; la canasta; el aro","hoop; basket"],["los esquís","skis"],["los guantes de boxeo","boxing gloves"],["el arquero","goalkeeper"],["el bateador","batter"],["el lanzador","pitcher"],["el porrista","cheerleader"],["el árbitro","umpire"],["batear","to bat"],["el boxeo","boxing"],["caerse","to fall"],["la carrera","race"],["la ginmasia","gymnastics"],["hacer un aro","to make a basket"],["la lucha","wrestling"],["saltar","to jump"],["practicar yoga","to do yoga"],["perder peso","to lose weight"],["subir de peso","to gain weight"],["usar las máquinas para hacer ejercicio","to use exercise machines"],["el básquetbol","basketball"],["el béisbol","baseball"],["el fútbol americano","football"],["ganar","to win"],["la natación","swimming"],["perder","to lose"],["el tenis","tennis"],["el voleibol","volleyball"],["el bate","bat"],["el casco","helmet"],["el guante","glove"],["los patines en línea","rollerblades"],["la pelota","ball"],["la raqueta","racket"],["los aficionados","fans"],["el campeón","champion (masculine)"],["la campeona","champion (feminine)"],["el campo","field"],["la cancha","court"],["el equipo","team"],["el ganador","winner"],["el jugador","player"],["doler","to hurt; to ache"],["fuerte","strong"],["heriod","hurt"],["la saldud","health"],["sano","healthy"]];
        var rw2=[["acostarse ","to go to bed"],["afeitarse ","to shave oneself"],["apagar la luz ","to turn off the light"],["arreglarse ","to get ready"],["bañarse ","to take a bath"],["cepillarse los dientes ","to brush one's teeth"],["despertarse ","to wake up"],["dormirse ","to fall asleep"],["ducharse ","to take a shower"],["encender la luz ","to turn on the light"],["entrenarse ","to train"],["lavarse ","to wash oneself"],["levantarse ","to get up"],["maquillarse ","to put on makeup"],["peinarse ","to comb one's hair"],["la rutina ","routine"],["secarse ","to dry oneself"],["tener prisa ","to be in a hurry"],["tener sueño ","to be sleepy"],["la cara ","face"],["el codo ","elbow"],["el cuello ","neck"],["el dedo ","finger"],["el dedo de pie ","toe"],["el diente ","tooth"],["la garaganta ","throat"],["el hombro ","schoulder"],["la muñeca ","wrist"],["el oído ","inner ear"],["la uña ","nail"],["el cepillo ","brush"],["el cepillo de dientes ","toothbrush"],["el champú ","shampoo"],["la crema de afeitar ","shaving cream"],["el desodorante ","deodorant"],["el jabón ","soap"],["la pasta de dientes ","toothpaste"],["el peine ","comb"],["el secador de pelo ","hair dryer"],["la toalla ","towel"],["primero ","first"],["entonces ","then; so"],["luego ","later; then"],["más tarde ","later on"],["por fin ","finally"],["a veces ","sometimes"],["frecuentemente ","frequently"],["generalmente ","in general; generally"],["normalmente ","usually; normally"],["la boca ","mouth"],["el brazo ","arm"],["la cabeza ","head"],["el corazón ","heart"],["el cuerpo ","body"],["el estómago ","stomach"],["la mano ","hand"],["la nariz ","nose"],["el ojo ","eye"],["lo oreja ","ear"],["el pelo ","hair"],["el pie ","foot"],["la piel ","skin"],["la pierna ","leg"],["la rodilla ","knee"],["el tobillo ","ankle"],["tener ","to have"],["tener ganas de ","to feel like"],["tener que ","to have to"],["alisarse el pelo ","to straighten one's hair"],["la base ","foundation"],["la colonia ","cologne"],["cortarse el pelo ","to cut one's hair"],["los cortaúñas ","nail clippers"],["el esmalte ","nailpolish"],["la loción para después de afeitarse ","aftershave"],["el perfume ","perfume"],["el pintalabios ","lipstick"],["el lápiz ","lipstick"],["pintarse el pelo ","to color one's hair"],["pintarse las uñas ","to color one's nails"],["el rímel ","mascara"],["rizarse el pelo ","to curl one's hair"],["la seda dental ","dental floss"],["la sombra de ojos ","eye shadow"],["los pulmones ","lungs"]];
        var raw=rw1.concat(rw2);
    }
    if(set==4){
        var raw=[["el abrigo ","coat"],["las botas ","boots"],["el chaleco ","vest"],["el cinturón ","belt"],["la falda ","skirt"],["la gorra ","cap"],["la pulsera ","bracelet"],["el reloj ","watch"],["las sandalias ","sandals"],["el suéter ","sweater"],["el traje ","suit"],["de cuadros ","plaid"],["de rayas ","striped"],["estar de moda ","to be in style"],["el número ","shoe size"],["la talla ","clothing size"],["vestirse ","to get dressed"],["¿Cómo me quedan? ","How do they fit me?"],["quedar ","to fit"],["bien ","well"],["mal ","badly"],["flojo ","loose"],["apretado ","tight"],["el almacén ","department store"],["la farmacia ","pharmacy"],["Internet ","Internet"],["la joyería ","jewelry store"],["la librería ","book store"],["la panadería ","bakery"],["la zapatería ","shoe store"],["Creo que sí. ","I believe so."],["Creo que no. ","I don't believe so."],["En mi opinion ","in my opinion"],["Es buena idea. ","It's a good idea."],["Es mala idea. ","It's a bad idea."],["Me parece que ","It seems to me that"],["encantar ","to delight"],["importar ","to be important"],["interesar ","to interest"],["recomendar ","to recommend"],["Está abierto. ","It's open."],["Está cerrado. ","It's closed."],["la bata ","bathrobe"],["la bufanda ","scarf"],["Billy la Bufanda ","Billy the Scarf"],["los guantes ","gloves"],["la minifalda ","miniskirt"],["los pantalones deportivos ","sweatpants"],["las pantuflas ","slippers"],["el pijama ","pajamas"],["el saco ","jacket"],["la sudadera ","(hooded) sweat shirt"],["corto ","short"],["largo ","long"],["ahorrar ","to save"],["la caja ","cash register"],["la carnicería ","butcher shop"],["el cheque de pago de sueldo ","pay check"],["la cuenta corriente ","checking account"],["el estipendio ","allowence"],["la juguetería ","toy store"],["la peluquería ","hair salon"],["el quiosco ","kiosk"],["el salón de belleza ","beauty salon"],["la tienda de discos ","music store"]];
    }
    if(set==5){
        var raw=[["los artículos","goods"],["barato","inexpensive"],["la escultura","sculpture"],["fino","fine"],["una ganga","a bargain"],["la pintura","painting"],["el retrato","portrait"],["único","unique"],["estar hecho a mano","to be handmade"],["ser de","to be made of"],["cerámica","ceramic"],["cuero","leather"],["madera","wood"],["metal","metal"],["oro","gold"],["piedra","stone"],["plata","silver"],["Con mucho gusto","With pleasure."],["Con permiso.","Excuse me."],["De nada.","You're welcome."],["Disculpe.","Excuse me."],["No hay de qué.","Don't mention it."],["Pase.","Go ahead."],["Perdóneme.","Forgive me."],["¿Me deja ver?","May I see?"],["delicado","delicate"],["el comprador","buyer"],["en venta","on sale"],["frágil","fragile"],["ofrecer","to offer"],["el pago","payment"],["pedir una rebaja","to ask for a lower price"],["el puesto","stand"],["rebajar el precio","to lower the price"],["el vendedor","seller"],["¿Me puede ayudar?","Can you help me?"],["Necesito ayuda.","I need help."]];
    }
    var ans=[];
    raw.forEach(function(v,i,a){ans.push([v[1].trim(),v[0].trim()]);});
    return ans;
}



//if(set==3){
//    var raw=    
//}